version: "3.0"

services:
  api:
    container_name: "ocr-api"
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8080:8080

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
