version: "3.0"

services:
  api:
    container_name: "ocr-api"
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8080:8080

  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  db-store: